### ISSUE TITLE
Parav Salaniwal - Big Project Feature Check #3 Goals

### ISSUE THREAD

**Issue by paravsalaniwal** [paravsalaniwal/praopersonal#17]
# Objective

The purpose of this final sprint is to fully implement the login stuff and integrate the login and signup page with the database and have it be accessible and used throughout all features. One big thing we need to work on is the role system within the login/signup and assigning the accurate permissions that each role has. We have faced difficulty throughout this process as we first struggled with the JWT cookie expiration and the cookie disappearing after going to a different feature. I want to be able to get the roles system down first with the appropriate permissions as well, and then focus on the integration with the login with all the features. 

## Tasks
- [ ] JWT Cookie expiration issue
- [ ] Assigning permissions within each role class
- [ ] Assign login to all features

### The Plan
**Requirements:**
- [ ] Roles under person database
- [ ] JWT token implementation
- [ ] Permissions per role
- [ ] Require JWT at each feature
- [ ] Create appealing login/signup frontend

## Schedule
- [ ] Monday: Permissions for each role
- [ ] Tuesday: Assigning roles to each user in database
- [ ] Wednesday: Finishing touches on backend and creating frontend
- [ ] Thursday: Testing in displaying the roles permissions
- [ ] Friday: Testing in displaying full login implementation with features

## What I will show
- Show the database with included role
- Show the permissions that each role has
    - Admin role can view all users of all roles
    - Employeer roles can see all other employers
    - Teacher can view the students that are in their class
    - Student can view themself only
